sonar.projectKey=crqcastro_bank-api
sonar.organization=crqcastro
sonar.projectName=bank-api
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=\
  **/BankApiApplication.java,\
  **/infrastructure/config/**,\
  **/domain/model/**,\
  **/adapter/in/web/**/request/**,\
  **/adapter/in/web/**/response/**
sonar.java.coveragePlugin=jacoco
sonar.qualitygate.wait=true
